language: Rust
cache: cargo
sudo: false
rust:
- nightly
- beta
- stable
before_script:
- export PATH=$HOME/.cargo/bin:$PATH
- rustup install nightly 
- type rustfmt || cargo +nightly install rustfmt-nightly
script:
# Fix rustfmt dll loading
- rustc +nightly --print sysroot
- ls $(rustc +nightly --print sysroot)/lib
- cargo build &&
  LD_LIBRARY_PATH=$(rustc +nightly --print sysroot)/lib:$LD_LIBRARY_PATH cargo test
env:
  global:
  - RUST_BACKTRACE=1

