language: Rust
cache: cargo
sudo: false
rust:
- nightly
before_script:
- export PATH=$HOME/.cargo/bin:$PATH
- type rustfmt || cargo install rustfmt
script:
- cargo test
env:
  global:
  - RUST_BACKTRACE=1
