[package]
name = "json-schema"
version = "0.1.0"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
build = "build.rs"

[workspace]

[dependencies]
quote = "0.3"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"

Inflector = "0.6.0"

[build-dependencies]
json-schema_snapshot = { path = "json-schema_snapshot" }

[features]
default = ["rustfmt"]
rustfmt = []
